export const MOVIES_INFO_SUCCESS = "MOVIE_INFO_SUCCESS";
export const MOVIES_INFO_REQUEST = "MOVIES_INFO_REQUEST";
export const MOVIES_INFO_ERROR = "MOVIES_INFO_ERROR";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_ERROR = "MOVIE_DETAILS_ERROR";
export const MOVIE_DETAILS_CLEAR = "MOVIE_DETAILS_CLEAR";

export const MOVIE_CHANGE_PAGE_NUMBER = "MOVIE_CHANGE_PAGE_NUMBER";