export const MOVIES_INFO_SUCCESS = 'MOVIE_INFO_SUCCESS';
export const MOVIES_INFO_REQUEST = 'MOVIES_INFO_REQUEST';
export const MOVIES_INFO_FAIL = 'MOVIES_INFO_FAIL';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
export const MOVIE_DETAILS_CLEAR = 'MOVIE_DETAILS_CLEAR';

export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
